[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["NODE_ENV= npm install"]

[phases.build]
cmds = [
  "npm run prisma:generate",
  "npm run build",
  "npm run prisma:migrate:deploy"
]

